[package]
name = "rustifile"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", feartures = ["derive"] }
serde_json = "1.0"
typetag = "0.2"
regex = "1.11"
tracing = "^0.1"
jaq-core = "^2"
